export const classesMap: { [key: string]: string } = {
  berserker: "Berserker",
  destroyer: "Destroyer",
  warlord: "Gunlancer",
  holyknight: "Paladin",
  berserker_female: "Slayer",
  arcana: "Arcanist",
  summoner: "Summoner",
  bard: "Bard",
  elemental_master: "Sorceress",
  battle_master: "Wardancer",
  infighter: "Scrapper",
  force_master: "Soulfist",
  lance_master: "Glaivier",
  battle_master_male: "Striker",
  infighter_male: "Breaker",
  blade: "Deathblade",
  demonic: "Shadowhunter",
  reaper: "Reaper",
  soul_eater: "Souleater",
  hawk_eye: "Sharpshooter",
  devil_hunter: "Deadeye",
  blaster: "Artillerist",
  scouter: "Machinist",
  devil_hunter_female: "Gunslinger",
  yinyangshi: "Artist",
  weather_artist: "Aeromancer",
};
