services:
  discord-bot:
    image: node:22.11.0
    container_name: discord-bot
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000' # Ajusta el puerto según sea necesario
    command: sh -c "npm install && npm run start" #
    networks:
      - discord-bot-network
    restart: unless-stopped

networks:
  discord-bot-network:
    driver: bridge
